### ISSUE TITLE
Bug adding a node to an existing workflow

### ISSUE THREAD

**Issue by tristandostaler** [Shuffle/openapi-apps#41]
Starting from the same workflow as in the bug https://github.com/Shuffle/openapi-apps/issues/40 I am trying to add a node "router" between node A and node B to see if that would fix. I delete the link between the 2 and add a Shuffle tool As soon as I select "Router", I get a blank windows with this error:
```
TypeError: Cannot read properties of null (reading 'find')
    at bundle.js:2:1723545
    at sl (bundle.js:2:2644966)
    at ks (bundle.js:2:2663780)
    at t.unstable_runWithPriority (bundle.js:2:2682022)
    at qa (bundle.js:2:2606849)
    at Cs (bundle.js:2:2663539)
    at ls (bundle.js:2:2655315)
    at bundle.js:2:2607140
    at t.unstable_runWithPriority (bundle.js:2:2682022)
    at qa (bundle.js:2:2606849)
Uncaught TypeError: Cannot read properties of null (reading 'find')
    at bundle.js:2:1723545
    at sl (bundle.js:2:2644966)
    at ks (bundle.js:2:2663780)
    at t.unstable_runWithPriority (bundle.js:2:2682022)
    at qa (bundle.js:2:2606849)
    at Cs (bundle.js:2:2663539)
    at ls (bundle.js:2:2655315)
    at bundle.js:2:2607140
    at t.unstable_runWithPriority (bundle.js:2:2682022)
    at qa (bundle.js:2:2606849)
```

I don't know if it's link, but just before changing to "router", just after adding the shuffle tool, I have a message in the console saying: 
```
Returning because node is not valid:  {id: (...)}
```

**Comment by tristandostaler** [comment]
Same bug on a completly new workflow with nothing else than a shuffle tool that I am trying to set as a router

**Comment by frikky** [comment]
> Same bug on a completly new workflow with nothing else than a shuffle tool that I am trying to set as a router

This is fixed for the next version, and is currently in testing. Should be out in the next few days. Thanks! 

It's also the exact reason Typescript is coming up more and more often internally ^_^

**Comment by tristandostaler** [comment]
I used typescript in the past and only have good things to say about it
